#!/usr/bin/env node
// shelly-frame.cjs — the write-time SUBSTRATE step.
//
// Turns an agent's bespoke INTERIOR (content + visual design + ballot markers) into a
// FRAME-COMPLETE artifact: the required mechanics are injected and guaranteed, never
// hand-carried. Called from `shelly-index.cjs` (which the PostToolUse hook already
// spawns once per artifact write) so framing costs no extra process on the hot path.
//
// The frame lives in frame/frame-core.html, GENERATED by frame/extract.mjs from
// plugin/skills/prefer-html/references/interaction-helper.md — the same text an agent
// pastes. The model never has to reproduce it; this step injects it.
//
// Guarantees (the "can't be missed" set), applied idempotently:
//   1. the unified helper (💬 comments + ✓/✎/✗ ballot → one `text:` submit) + size reporter
//   2. a fallback light app-shade background — zero-specificity, so it never overrides
//      the artifact's own paint and a curated shell repaint (SKILL.md §5) still works
//   3. 💬 ambient comments on every block  (data-shelly-commentable auto-ensured)
//   4. no dead submit: any agent script posting `payload:` (not `text:`) is stripped
//   5. no black card: dark-mode background overrides are stripped
//
// The LOOK is never touched — only mechanics.
//
// WHY WRITE-TIME AND NOT RENDER-TIME. The Board could inject this as it loads each
// artifact, which would save ~55 KB per file and let a frame fix reach every PAST
// artifact retroactively. Two things decide it the other way. Artifacts load over
// `asset://` — a direct file read, so there is no interception point without writing a
// custom protocol handler — and, the real reason, a Shelly artifact is promised to be
// SELF-CONTAINED: it must still work opened straight in a browser, which a
// render-time-only frame would silently break. Write-time also ships as a plugin bump
// rather than an app rebuild, so it reaches users without a reinstall.
//
// Usage (manual / tests): node shelly-frame.cjs <file.html>

const fs = require("fs");
const path = require("path");

const FRAME_PATH = path.join(__dirname, "frame", "frame-core.html");
const FRAME_MARK = "SHELLY-FRAME-START";
const FRAME_END = "SHELLY-FRAME-END";
const PLACEHOLDER_RE = /<!--\s*shelly-frame\s*-->/i;
/** `<!-- SHELLY-FRAME-START v=abc12345 … -->` → "abc12345" (null on an unstamped frame). */
const VERSION_RE = /SHELLY-FRAME-START\s+v=([0-9a-f]+)/;

/** Remove a `<script>` block that posts a submit as `payload:` (no `text:`) — a dead button.
 *  The injected frame owns the one correct submit, so a competing hand-rolled one must go.
 *  (The frame also vetoes ballot clicks in the capture phase, so such a script is already
 *  inert — but dead code that flashes "Sent ✓" at the user is worth deleting outright.) */
function stripPayloadSubmit(html) {
  return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, (block) => {
    if (block.includes(FRAME_MARK)) return block; // never touch the frame's own scripts
    const postsSubmit = /kind:\s*["']submit["']/.test(block);
    const hasText = /\btext:/.test(block);
    const hasPayload = /\bpayload:/.test(block);
    if (postsSubmit && hasPayload && !hasText) return ""; // drop the dead-wire script
    return block;
  });
}

/** Strip `@media (prefers-color-scheme: dark){…}` blocks that override a background —
 *  the "all black" bug. Brace-matched so nested rules are removed cleanly. */
function stripDarkBg(html) {
  const marker = /@media[^{]*prefers-color-scheme:\s*dark[^{]*\{/gi;
  let out = html, m;
  while ((m = marker.exec(out))) {
    const start = m.index;
    let i = m.index + m[0].length - 1; // at the opening brace
    let depth = 0;
    for (; i < out.length; i++) {
      if (out[i] === "{") depth++;
      else if (out[i] === "}") { depth--; if (depth === 0) break; }
    }
    const block = out.slice(start, i + 1);
    if (/background/i.test(block)) {
      out = out.slice(0, start) + out.slice(i + 1);
      marker.lastIndex = start;
    }
  }
  return out;
}

/** Match an attribute only where it sits INSIDE AN OPENING TAG — `<main data-fit-root>` —
 *  and never where the same characters appear in CSS or script text. `[^<>]*?` is what
 *  enforces that: it cannot cross the `>` that closes `<style>` or `<script>`.
 *
 *  This is not defensive over-engineering; it is a bug that shipped. `ensureCommentable`
 *  used to replace the FIRST occurrence of the bare string `data-fit-root`, and in every
 *  template in the skill the first occurrence is the CSS selector in <head>:
 *  `[data-fit-root]{width:900px}`. So the tag became the nonsense selector
 *  `[data-fit-root data-shelly-commentable]`, the real wrapper was never marked, and the
 *  artifact rendered with NO 💬 at all — the exact failure the frame exists to prevent,
 *  reintroduced by the fix. Every unit test passed; only a real browser render caught it. */
function attrInTag(name) {
  return new RegExp(`(<[a-zA-Z][^<>]*?\\b${name}\\b)`);
}
const FIT_ROOT_ATTR = attrInTag("data-fit-root");
const COMMENTABLE_ATTR = attrInTag("data-shelly-commentable");

/** Guarantee 💬: if the interior marked nothing commentable, make the whole content region
 *  commentable by tagging the [data-fit-root] wrapper. The helper skips anything inside
 *  [data-shelly-item], so this can never put comment icons on the ballot.
 *
 *  Both tests are markup-scoped for the same reason: an artifact that pasted the ambient
 *  CSS (which contains a `[data-shelly-commentable]` SELECTOR) but marked no element would
 *  otherwise look "already commentable" and be skipped — inert markup, no icons. */
function ensureCommentable(html) {
  if (COMMENTABLE_ATTR.test(html)) return html;
  if (FIT_ROOT_ATTR.test(html)) {
    return html.replace(FIT_ROOT_ATTR, "$1 data-shelly-commentable");
  }
  return html; // no fit-root element → left for the gate to flag
}

/** The frame version stamped into `html`, or null when it carries no frame. */
function frameVersion(html) {
  const m = VERSION_RE.exec(html);
  return m ? m[1] : null;
}

/** Cut an existing frame block out, marker to marker, leaving the placeholder behind.
 *  Used ONLY to replace a stale frame during a write that is happening anyway — never as
 *  a retroactive rewrite of an artifact the user may be reading, which would destroy the
 *  💬 comments they typed into it (those live only in that iframe's DOM). */
function removeFrame(html) {
  const start = html.indexOf(`<!-- ${FRAME_MARK}`);
  if (start === -1) return html;
  const endMark = html.indexOf(`<!-- ${FRAME_END} -->`);
  if (endMark === -1 || endMark < start) return html; // truncated frame — leave it alone
  const end = endMark + `<!-- ${FRAME_END} -->`.length;
  return html.slice(0, start) + "<!-- shelly-frame -->" + html.slice(end);
}

/** Inject the frame at the placeholder, else before </body>, else append.
 *  Idempotent, and version-aware: a frame left by an older plugin is swapped for the
 *  current one, so `claude plugin update` takes effect on the next write instead of
 *  only on artifacts created after it. */
function ensureFrame(html, frame) {
  if (html.includes(FRAME_MARK)) {
    const have = frameVersion(html);
    const want = frameVersion(frame);
    if (!want || have === want) return html; // already current (or an unstamped frame)
    html = removeFrame(html);
    if (html.includes(FRAME_MARK)) return html; // couldn't excise it — don't stack two
  }
  if (PLACEHOLDER_RE.test(html)) return html.replace(PLACEHOLDER_RE, frame);
  if (/<\/body>/i.test(html)) return html.replace(/<\/body>/i, frame + "\n</body>");
  return html + "\n" + frame;
}

/** Full transform: de-hazard the interior, then inject the guaranteed frame. */
function applyFrame(html, frame) {
  let out = html;
  out = stripPayloadSubmit(out);
  out = stripDarkBg(out);
  out = ensureCommentable(out);
  out = ensureFrame(out, frame);
  return out;
}

let cachedFrame;
/** Read (and memoise) the frame asset. `null` when it can't be read — callers then leave
 *  the artifact alone rather than half-framing it. */
function loadFrame() {
  if (cachedFrame !== undefined) return cachedFrame;
  try {
    cachedFrame = fs.readFileSync(FRAME_PATH, "utf8");
  } catch (_) {
    cachedFrame = null;
  }
  return cachedFrame;
}

/** The call sites' entry point: html → framed html. Fail-safe by construction — returns
 *  the input unchanged on any problem, so a frame fault can never cost a user an artifact. */
function frameArtifact(html) {
  try {
    const frame = loadFrame();
    if (!frame) return html;
    return applyFrame(html, frame);
  } catch (_) {
    return html;
  }
}

function main() {
  const file = process.argv[2];
  if (!file) { process.stderr.write("usage: shelly-frame.cjs <file.html>\n"); process.exit(2); }
  let html;
  try { html = fs.readFileSync(file, "utf8"); }
  catch (_) { process.exit(0); } // mid-write / gone — fail open, index step still runs
  const next = frameArtifact(html);
  if (next !== html) {
    try { fs.writeFileSync(file, next); } catch (_) { /* best-effort */ }
  }
}

if (require.main === module) main();
module.exports = {
  applyFrame, frameArtifact, ensureFrame, ensureCommentable,
  stripPayloadSubmit, stripDarkBg, frameVersion, removeFrame,
  FRAME_MARK, FRAME_PATH,
};
